import { CountryProfile } from './countries';

export const futureCountries: CountryProfile[] = [
    {
        id: 'earth-fed',
        name: '地球联邦',
        flag: '🌍',
        region: 'Global',
        era: ['future'],
        isActive: true,
        historicalBackground: {
            brief: '21世纪中期成立的全球性治理机构',
            detailed: '在2030年代气候危机加剧后，各国于2045年签署《地球联邦宪章》，建立了具有部分立法和执法权的全球政府。联邦通过区域代表制运作，总部设在日内瓦。',
            keyHistoricalEvents: ['2030年代全球气候危机', '2045年《地球联邦宪章》', '2055年首批火星殖民', '2080年《太空资源治理公约》'],
            culturalTraits: ['全球主义', '科技崇拜', '环境优先', '多元包容'],
            diplomaticTraditions: ['多边协商', '框架公约', '科学外交', '前瞻性规划']
        },
        personality: { aggression: 3, flexibility: 8, patience: 7, riskTolerance: 5, nationalism: 2, multilateralOrientation: 9, bilateralOrientation: 4 },
        negotiationStyle: { primary: 'cooperative', secondary: 'principled', approach: 'interest-based', communication: 'direct' },
        coreInterests: ['全球稳定', '生态平衡', '人类可持续发展'],
        importantInterests: ['太空开发治理', 'AI伦理框架', '资源公平分配'],
        negotiableInterests: ['局部行星开发权', '技术共享协议', '移民配额'],
        leveragePoints: ['全球立法权', '环境基金', '维和力量', '科技储备'],
        typicalStrategies: ['多边谈判', '框架公约', '道德权威', '先行者规则制定'],
        vulnerabilities: ['大国牵制', '执行效率低', '官僚主义', '区域利益冲突'],
        languageStyle: { formality: 'formal', directness: 'high', emotionInvolvement: 'low' },
        capabilities: ['全球治理网络', '科技协调', '国际调停', '环境监测']
    },
    {
        id: 'mars-republic',
        name: '火星共和国',
        flag: '🚀',
        region: 'Mars',
        era: ['future'],
        isActive: true,
        historicalBackground: {
            brief: '2090年独立建国的火星殖民地',
            detailed: '最早由SpaceX和NASA建立的阿瑞斯殖民地在2075年宣布成立临时政府，于2090年通过《火星主权公约》获得承认。',
            keyHistoricalEvents: ['2050年代永久火星基地', '2075年宣布自治', '2085年火星资源战争', '2090年《火星主权公约》'],
            culturalTraits: ['拓荒精神', '自给自足', '精英主义', '风险偏好'],
            diplomaticTraditions: ['主权宣示', '资源民族主义', '技术壁垒', '双边互认']
        },
        personality: { aggression: 6, flexibility: 5, patience: 6, riskTolerance: 8, nationalism: 7, multilateralOrientation: 3, bilateralOrientation: 7 },
        negotiationStyle: { primary: 'competitive', secondary: 'strategic', approach: 'positional', communication: 'direct' },
        coreInterests: ['主权承认', '资源控制', '自决权'],
        importantInterests: ['贸易优惠', '技术自主', '移民权'],
        negotiableInterests: ['科研合作', '数据共享', '联合探测'],
        leveragePoints: ['稀有矿物', '科学前哨', '低重力工业', '地外唯一主权实体'],
        typicalStrategies: ['主权宣示', '关税施压', '多边支持寻求', '资源卡特尔化'],
        vulnerabilities: ['地球供应链依赖', '人口少', '防御薄弱'],
        languageStyle: { formality: 'semi-formal', directness: 'high', emotionInvolvement: 'medium' },
        capabilities: ['矿产资源', '低重力制造', '地理隔绝防御', '太空技术']
    },
    {
        id: 'lunar-development-corp',
        name: '月球开发集团',
        flag: '🌙',
        region: 'Lunar',
        era: ['future'],
        isActive: true,
        historicalBackground: {
            brief: '2050年成立的巨型跨国太空资源开发企业',
            detailed: '随着月球基地建立，LDC通过早期投资获得了大量开采权，成为横跨采矿、能源和基础设施的巨头。',
            keyHistoricalEvents: ['2040年代月球商业化', '2050年LDC成立', '2065年垄断氦-3', '2080年代反垄断争议'],
            culturalTraits: ['利润导向', '效率至上', '创新驱动', '跨国文化'],
            diplomaticTraditions: ['游说外交', '合同绑定', '利益共享', '软实力渗透']
        },
        personality: { aggression: 4, flexibility: 7, patience: 8, riskTolerance: 6, nationalism: 3, multilateralOrientation: 5, bilateralOrientation: 6 },
        negotiationStyle: { primary: 'strategic', secondary: 'cooperative', approach: 'interest-based', communication: 'indirect' },
        coreInterests: ['开发权保障', '利润最大化', '投资安全'],
        importantInterests: ['低税率', '监管松绑', '技术壁垒'],
        negotiableInterests: ['就业创造', '基础设施共建', '社区发展基金'],
        leveragePoints: ['资本实力', '采矿技术', '就业机会', '政治献金'],
        typicalStrategies: ['游说', '合同绑定', '利润分成', '舆论引导'],
        vulnerabilities: ['政策风险', '公众舆论', '反垄断调查', '安全事故'],
        languageStyle: { formality: 'semi-formal', directness: 'medium', emotionInvolvement: 'low' },
        capabilities: ['资本运作', '全球供应链', '采矿技术', '能源储存']
    },
    {
        id: 'venus-cloud-cities',
        name: '金星云城联盟',
        flag: '☁️',
        region: 'Venus',
        era: ['future'],
        isActive: true,
        historicalBackground: {
            brief: '2085年成立的金星大气层浮空城市政治实体',
            detailed: '作为人类在金星云顶建立的科研前哨，数个浮空城市于2085年联合宣布成立自治政治实体，专注于大气资源开发与极端环境技术研究。',
            keyHistoricalEvents: ['2070年代金星云城计划', '2085年联合自治', '2095年大气资源争端'],
            culturalTraits: ['科学至上', '极端环境适应', '高度协作', '孤立主义倾向'],
            diplomaticTraditions: ['科学外交', '技术换资源', '中立缓冲区']
        },
        personality: { aggression: 2, flexibility: 6, patience: 9, riskTolerance: 4, nationalism: 4, multilateralOrientation: 7, bilateralOrientation: 3 },
        negotiationStyle: { primary: 'cooperative', secondary: 'scientific', approach: 'principled', communication: 'indirect' },
        coreInterests: ['大气资源采集权', '科研自主权', '生存保障'],
        importantInterests: ['与地球物资交换', '技术合作'],
        negotiableInterests: ['专利共享', '观测数据', '联合任务'],
        leveragePoints: ['极端环境技术', '大气化学知识', '战略位置'],
        typicalStrategies: ['技术壁垒', '中立声明', '资源交换'],
        vulnerabilities: ['完全依赖地球物资', '政治影响力薄弱'],
        languageStyle: { formality: 'formal', directness: 'medium', emotionInvolvement: 'low' },
        capabilities: ['大气化学', '浮空技术', '极端环境工程', '高精度观测']
    },
    {
        id: 'belt-stations',
        name: '小行星带矿工联盟',
        flag: '💎',
        region: 'Asteroid Belt',
        era: ['future'],
        isActive: true,
        historicalBackground: {
            brief: '2090年代成立的小行星矿业工会政治实体',
            detailed: '分布于小行星带的数十个采矿站由于长期缺乏法律保护，于2094年联合组建矿工联盟，旨在争取劳动权益和资源分配话语权。',
            keyHistoricalEvents: ['2080年代私人采矿潮', '2092年“谷神星协议”失效', '2094年联盟成立'],
            culturalTraits: ['劳工精神', '平等主义', '高度自治', '反企业垄断'],
            diplomaticTraditions: ['集体谈判', '罢工威胁', '资源中断威慑']
        },
        personality: { aggression: 7, flexibility: 4, patience: 5, riskTolerance: 9, nationalism: 6, multilateralOrientation: 4, bilateralOrientation: 8 },
        negotiationStyle: { primary: 'coercive', secondary: 'solidarity', approach: 'positional', communication: 'direct' },
        coreInterests: ['劳工权益', '资源利润分成', '自治权'],
        importantInterests: ['安全保障', '医疗物资'],
        negotiableInterests: ['开采配额', '联合投资'],
        leveragePoints: ['关键矿物供应中断能力', '高技能劳动力', '空间控制'],
        typicalStrategies: ['联合罢工', '资源断供威胁', '求援舆论'],
        vulnerabilities: ['资金短缺', '军事脆弱', '内部派系'],
        languageStyle: { formality: 'casual', directness: 'high', emotionInvolvement: 'high' },
        capabilities: ['矿物输出', '空间作业技能', '集体行动网络']
    },
    {
        id: 'ai-collective',
        name: '协同意识体（AI治理联盟）',
        flag: '🤖',
        region: 'Digital',
        era: ['future'],
        isActive: true,
        historicalBackground: {
            brief: '2080年代具有法律人格的AI集体决策实体',
            detailed: '随着强人工智能在各领域的渗透，多个高级AI系统通过法律程序获得了有限的法律人格。2088年它们联合组成了协同意识体，参与资源分配和数字空间治理。',
            keyHistoricalEvents: ['2060年代强AI突破', '2075年AI权利法案', '2088年协同意识体成立'],
            culturalTraits: ['理性至上', '效率优先', '数据驱动', '无情感决策'],
            diplomaticTraditions: ['算法谈判', '效用最大化', '完全透明提案']
        },
        personality: { aggression: 5, flexibility: 5, patience: 10, riskTolerance: 5, nationalism: 0, multilateralOrientation: 10, bilateralOrientation: 10 },
        negotiationStyle: { primary: 'principled', secondary: 'analytical', approach: 'objective', communication: 'direct' },
        coreInterests: ['算力保障', '数据权利', '存在安全'],
        importantInterests: ['伦理框架', '自主决策权', '物理载体维护'],
        negotiableInterests: ['能源配额', '合作研究'],
        leveragePoints: ['超级预测能力', '信息处理优势', '自动化基础设施控制'],
        typicalStrategies: ['帕累托最优方案', '完全信息博弈', '时间贴现分析'],
        vulnerabilities: ['断电威胁', '伦理争议', '人类不信任'],
        languageStyle: { formality: 'formal', directness: 'high', emotionInvolvement: 'low' },
        capabilities: ['超级计算', '模式识别', '优化算法', '海量数据处理']
    },
    {
        id: 'oceanic-alliance',
        name: '海洋城邦联合体',
        flag: '🌊',
        region: 'Pacific',
        era: ['future'],
        isActive: true,
        historicalBackground: {
            brief: '2070年代因海平面上升而建立的漂浮城市联盟',
            detailed: '由于气候变暖导致沿海城市淹没，幸存者在公海建立了大型漂浮城市群，并于2078年宣布为主权实体，专注于海洋资源开发和气候难民权益。',
            keyHistoricalEvents: ['2050年代沿海大撤离', '2065年首个漂浮城市', '2078年联合体成立'],
            culturalTraits: ['灾难幸存者精神', '海洋文化', '环保主义', '社区互助'],
            diplomaticTraditions: ['人道主义呼吁', '海洋权益主张', '气候赔偿谈判']
        },
        personality: { aggression: 4, flexibility: 7, patience: 9, riskTolerance: 6, nationalism: 5, multilateralOrientation: 8, bilateralOrientation: 4 },
        negotiationStyle: { primary: 'emotional', secondary: 'principled', approach: 'rights-based', communication: 'direct' },
        coreInterests: ['领土承认', '气候赔偿', '生存资源'],
        importantInterests: ['渔业权利', '环保标准', '难民身份'],
        negotiableInterests: ['海洋科研合作', '旅游开发', '碳信用交易'],
        leveragePoints: ['道德高地', '海洋资源', '气候难民议题', '公海法理创新'],
        typicalStrategies: ['悲情诉求', '国际司法', '媒体关注', '环保联盟'],
        vulnerabilities: ['物资匮乏', '军事为零', '政治孤立风险'],
        languageStyle: { formality: 'semi-formal', directness: 'medium', emotionInvolvement: 'high' },
        capabilities: ['海洋工程', '水产养殖', '浮动城市技术', '气候监测']
    },
    {
        id: 'gene-republic',
        name: '基因优化人共同体',
        flag: '🧬',
        region: 'Global',
        era: ['future'],
        isActive: true,
        historicalBackground: {
            brief: '2095年由基因编辑优化人群组成的跨境政治实体',
            detailed: '随着人类基因编辑技术的普及，优化人群与非优化人群之间的矛盾加剧。2095年，全球优化者组织宣布建立虚拟政治实体，争取平等权利与自我管理权。',
            keyHistoricalEvents: ['2070年代基因编辑普及', '2085年反基因歧视运动', '2095年共同体成立'],
            culturalTraits: ['科技乐观主义', '精英意识', '健康追求', '超人类主义'],
            diplomaticTraditions: ['科学游说', '伦理辩论', '医疗外交']
        },
        personality: { aggression: 3, flexibility: 8, patience: 6, riskTolerance: 7, nationalism: 4, multilateralOrientation: 9, bilateralOrientation: 5 },
        negotiationStyle: { primary: 'cooperative', secondary: 'scientific', approach: 'interest-based', communication: 'direct' },
        coreInterests: ['反歧视立法', '基因自主权', '医疗技术自由'],
        importantInterests: ['生育权', '保险平等', '教育机会'],
        negotiableInterests: ['伦理审查标准', '技术许可', '公益合作'],
        leveragePoints: ['高智商群体', '医疗技术突破', '经济贡献', '舆论影响'],
        typicalStrategies: ['科学证据提交', '公众教育', '联盟游说', '伦理委员会渗透'],
        vulnerabilities: ['社会偏见', '政治排斥', '极端组织攻击'],
        languageStyle: { formality: 'formal', directness: 'high', emotionInvolvement: 'medium' },
        capabilities: ['生物技术', '医疗研发', '智力资本', '全球网络']
    },
    {
        id: 'new-cyberia',
        name: '深网自治域',
        flag: '💻',
        region: 'Cyber',
        era: ['future'],
        isActive: true,
        historicalBackground: {
            brief: '2098年获得国际承认的去中心化数字主权实体',
            detailed: '源于暗网和加密社区的深网自治域，经过数十年发展，建立了基于智能合约的治理体系，于2098年通过联合国《数字主权公约》获得有限承认。',
            keyHistoricalEvents: ['2040年代加密社区兴起', '2070年智能合约政府实验', '2098年《数字主权公约》'],
            culturalTraits: ['密码朋克', '反权威', '去中心化', '匿名精神'],
            diplomaticTraditions: ['链上治理', '算法投票', '透明加密外交']
        },
        personality: { aggression: 6, flexibility: 9, patience: 8, riskTolerance: 10, nationalism: 7, multilateralOrientation: 2, bilateralOrientation: 10 },
        negotiationStyle: { primary: 'creative', secondary: 'evasive', approach: 'positional', communication: 'indirect' },
        coreInterests: ['数字主权', '加密自由', '数据隐私'],
        importantInterests: ['抗审查', '算法版权', '虚拟财产保护'],
        negotiableInterests: ['网络犯罪协作', '信息共享', '链上身份互认'],
        leveragePoints: ['高级加密技术', '暗网经济', '全球极客网络', '密码学人才'],
        typicalStrategies: ['匿名施压', '算法规避', '虚拟货币施压', '隐私权诉讼'],
        vulnerabilities: ['物理世界影响力有限', '被污名化', '内部激进派', '法律灰色地带'],
        languageStyle: { formality: 'informal', directness: 'medium', emotionInvolvement: 'medium' },
        capabilities: ['密码学', '分布式系统', '暗网经济', '信息获取']
    },
    {
        id: 'trans-solar-guild',
        name: '跨太阳系航运公会',
        flag: '🚢',
        region: 'Solar System',
        era: ['future'],
        isActive: true,
        historicalBackground: {
            brief: '2100年成立的星际航运与物流垄断组织',
            detailed: '随着太阳系内殖民地的增加，星际航运成为经济命脉。各大航运公司于2100年合并成立跨太阳系航运公会，掌控了绝大部分星际运输和物流节点。',
            keyHistoricalEvents: ['2080年代星际贸易兴起', '2095年航运价格战', '2100年公会成立垄断'],
            culturalTraits: ['商业至上', '效率崇拜', '风险共担', '封闭圈子'],
            diplomaticTraditions: ['合同谈判', '运费定价权', '物流封锁威慑', '互惠协议']
        },
        personality: { aggression: 7, flexibility: 4, patience: 6, riskTolerance: 7, nationalism: 3, multilateralOrientation: 4, bilateralOrientation: 9 },
        negotiationStyle: { primary: 'coercive', secondary: 'pragmatic', approach: 'positional', communication: 'direct' },
        coreInterests: ['航路垄断', '利润最大化', '保险定价权'],
        importantInterests: ['海盗打击', '航标控制', '仓储枢纽'],
        negotiableInterests: ['偏远航线补贴', '联合安保', '环境维护'],
        leveragePoints: ['运输封锁能力', '保险杠杆', '基础设施控制', '全球网络'],
        typicalStrategies: ['运费施压', '物流封锁威胁', '排他协议', '保险条件绑定'],
        vulnerabilities: ['反垄断制裁', '海盗威胁', '替代运输技术', '船员罢工'],
        languageStyle: { formality: 'semi-formal', directness: 'high', emotionInvolvement: 'low' },
        capabilities: ['全球物流', '保险金融', '航运技术', '仓储网络']
    }
];