'use client';

import React, { useState } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { 
  NegotiationTopic, 
  Party, 
  GeneratedScenario, 
  NegotiationIssue, 
  NegotiationGoals,
  BilateralDifficulty,
  DIFFICULTY_DESCRIPTIONS
} from '@/types/negotiation';
import { negotiationTopics, countries, personalityPresets, historicalBackgrounds, coldWarTopics } from '@/lib/negotiation-data';
import { futureTopics, futureCategories } from '@/lib/future-topics';
import { historicalCountries } from '@/lib/historical-countries';
import { ERA_CONFIGS, getEraConfig } from '@/lib/era-config';
import { getCountryById } from '@/lib/countries';
import { HistoricalEra } from '@/types/negotiation';
import CustomScenarioUploader from './CustomScenarioUploader';
import { 
  Sparkles, 
  Check, 
  Globe, 
  Rocket, 
  Clock, 
  Building2,
  BookOpen,
  Target,
  ListOrdered,
  ChevronDown,
  ChevronUp,
  RefreshCw,
  Loader2,
  AlertCircle,
  GripVertical
} from 'lucide-react';
import { futureCountries } from '@/lib/future-countries';

interface CustomScenario {
  title: string;
  description: string;
  timePeriod: string;
  parties: {
    self: string;
    opponent: string;
  };
  context: string;
  keyIssues: string[];
  background?: string;
}

interface ConfigWizardProps {
  onComplete: (config: {
    topic: NegotiationTopic;
    selfParty: Party;
    opponentParty: Party;
    objectives: string[];
    customScenario?: CustomScenario;
    background?: GeneratedScenario;
    goals?: NegotiationGoals;
    issues?: NegotiationIssue[];
    difficulty: BilateralDifficulty;
    era?: HistoricalEra;
  }) => void;
}

type Step = 'topic' | 'parties' | 'era' | 'background' | 'goals' | 'issues' | 'complete';
type TopicFilter = 'all' | 'modern' | 'cold-war' | 'future';

export default function ConfigWizard({ onComplete }: ConfigWizardProps) {
  const [currentStep, setCurrentStep] = useState<Step>('topic');
  const [selectedTopic, setSelectedTopic] = useState<NegotiationTopic | null>(null);
  const [selfCountry, setSelfCountry] = useState<string>('');
  const [opponentCountry, setOpponentCountry] = useState<string>('');
  const [opponentPersonality, setOpponentPersonality] = useState<string>('');
  // const [difficulty, setDifficulty] = useState<BilateralDifficulty>('medium');
  const difficulty: BilateralDifficulty = 'hard';
  const [objectives, setObjectives] = useState<string[]>([]);
  const [newObjective, setNewObjective] = useState('');
  const [customScenario, setCustomScenario] = useState<CustomScenario | null>(null);
  const [showCustomUploader, setShowCustomUploader] = useState(false);
  const [topicFilter, setTopicFilter] = useState<TopicFilter>('all');
  const [selectedFutureCategory, setSelectedFutureCategory] = useState<string>('all');
  const [showTopicDetails, setShowTopicDetails] = useState<string | null>(null);
  const [selectedEra, setSelectedEra] = useState<HistoricalEra>('modern');

  const [highCaseTitle, setHighCaseTitle] = useState('');
  const [highCaseDesc, setHighCaseDesc] = useState('');
  const [middleCaseTitle, setMiddleCaseTitle] = useState('');
  const [middleCaseDesc, setMiddleCaseDesc] = useState('');
  const [bottomLineTitle, setBottomLineTitle] = useState('');
  const [bottomLineDesc, setBottomLineDesc] = useState('');

  const updateHighCase = (title: string, desc: string) => {
    setHighCase(`${title}\n\n${desc}`);
  };
  const updateMiddleCase = (title: string, desc: string) => {
    setWinWinCase(`${title}\n\n${desc}`);
  };
  const updateBottomLine = (title: string, desc: string) => {
    setBottomLine(`${title}\n\n${desc}`);
  };

  // 背景生成相关状态
  const [generatedBackground, setGeneratedBackground] = useState<GeneratedScenario | null>(null);
  const [isGeneratingBackground, setIsGeneratingBackground] = useState(false);
  const [backgroundError, setBackgroundError] = useState<string | null>(null);

  // 目标设定相关状态
  const [highCase, setHighCase] = useState('');
  const [bottomLine, setBottomLine] = useState('');
  const [winWinCase, setWinWinCase] = useState('');
  
  // AI生成目标相关状态
  const [autoGeneratedGoals, setAutoGeneratedGoals] = useState<{
    highCase: string;
    middleCase: string;
    bottomLine: string;
  } | null>(null);
  const [isGeneratingGoals, setIsGeneratingGoals] = useState(false);
  const [goalsError, setGoalsError] = useState<string | null>(null);
  
  // AI生成方案相关状态（进阶模式）
  const [proposals, setProposals] = useState<any[]>([]);
  const [selectedHighProposal, setSelectedHighProposal] = useState<string | null>(null);
  const [selectedMiddleProposal, setSelectedMiddleProposal] = useState<string | null>(null);
  const [selectedBottomLineProposal, setSelectedBottomLineProposal] = useState<string | null>(null);
  const [isGeneratingProposals, setIsGeneratingProposals] = useState(false);
  const [proposalsError, setProposalsError] = useState<string | null>(null);

  // 议题相关状态
  const [issues, setIssues] = useState<NegotiationIssue[]>([]);
  const [expandedIssue, setExpandedIssue] = useState<string | null>(null);

  // 步骤定义
  const steps: { key: Step; label: string }[] = [
    { key: 'topic', label: '谈判主题' },
    { key: 'parties', label: '参与方' },
    { key: 'era', label: '历史时期' },
    // { key: 'difficulty', label: '难度选择' },
    { key: 'background', label: '背景故事' },
    { key: 'goals', label: '目标设定' },
    { key: 'issues', label: '议题顺序' },
    { key: 'complete', label: '准备完成' },
  ];

  // 合并所有国家（包括历史国家）
  const allCountries = [
    ...countries,
    ...historicalCountries.map(hc => ({
      id: hc.id,
      name: hc.name,
      region: hc.region,
      flag: hc.flag,
      isHistorical: true,
    })),
  ];


  const currentStepIndex = steps.findIndex((s) => s.key === currentStep);

  const handleNext = () => {
    const nextIndex = currentStepIndex + 1;
    if (nextIndex < steps.length) {
      setCurrentStep(steps[nextIndex].key);
    }
  };

  const handleBack = () => {
    const prevIndex = currentStepIndex - 1;
    if (prevIndex >= 0) {
      setCurrentStep(steps[prevIndex].key);
    }
  };

  const handleComplete = () => {
    if (!selectedTopic || !selfCountry || !opponentCountry) return;

    // 查找完整国家档案（包括历史国家）
    const selfCountryData = getCountryById(selfCountry) || 
      historicalCountries.find((c) => c.id === selfCountry);
    const opponentCountryData = getCountryById(opponentCountry) ||
      historicalCountries.find((c) => c.id === opponentCountry);
    
    const selfParty: Party = {
      name: selfCountryData?.name || customScenario?.parties.self || '',
      country: selfCountry,
      role: 'diplomat',
      // 传递完整国家档案
      ...(selfCountryData ? {
        personality: selfCountryData.personality,
        negotiationStyle: selfCountryData.negotiationStyle,
        coreInterests: selfCountryData.coreInterests,
        importantInterests: selfCountryData.importantInterests,
        negotiableInterests: selfCountryData.negotiableInterests,
        leveragePoints: selfCountryData.leveragePoints,
        typicalStrategies: selfCountryData.typicalStrategies,
        vulnerabilities: selfCountryData.vulnerabilities,
        languageStyle: selfCountryData.languageStyle,
        capabilities: selfCountryData.capabilities,
      } : {}),
    };

    const selectedPreset = personalityPresets.find((p) => p.name === opponentPersonality);
    const opponentCountryId = customScenario?.parties.opponent && !countries.find(c => c.name === customScenario.parties.opponent)
      ? 'custom'
      : opponentCountry;
    
    // 获取历史背景
    const opponentHistoricalCountry = historicalCountries.find((c) => c.id === opponentCountry);
    const opponentBackground = opponentHistoricalCountry?.historicalBackground.detailed || 
      historicalBackgrounds[opponentCountry] || 
      customScenario?.context || 
      '';

    const opponentParty: Party = {
      name: opponentCountryData?.name || customScenario?.parties.opponent || '',
      country: opponentCountry,
      role: 'diplomat',
      // 传递完整国家档案（优先使用数据库中的，fallback到预设性格）
      ...(opponentCountryData ? {
        personality: opponentCountryData.personality,
        negotiationStyle: opponentCountryData.negotiationStyle,
        coreInterests: opponentCountryData.coreInterests,
        importantInterests: opponentCountryData.importantInterests,
        negotiableInterests: opponentCountryData.negotiableInterests,
        leveragePoints: opponentCountryData.leveragePoints,
        typicalStrategies: opponentCountryData.typicalStrategies,
        vulnerabilities: opponentCountryData.vulnerabilities,
        languageStyle: opponentCountryData.languageStyle,
        capabilities: opponentCountryData.capabilities,
        historicalBackground: opponentCountryData.historicalBackground?.detailed || 
          opponentCountryData.historicalBackground || 
          opponentBackground,
      } : {
        personality: selectedPreset?.traits,
        historicalBackground: opponentBackground,
      }),
    };

    // 构建目标对象
    const goals: NegotiationGoals = {
      highCase: highCase || objectives.filter(o => o.includes('理想')).join('；') || '争取最大利益',
      bottomLine: bottomLine || objectives.filter(o => o.includes('底线')).join('；') || '守住核心利益',
      winWinCase: winWinCase || objectives.filter(o => o.includes('共赢')).join('；') || '寻求双方都能接受的方案',
    };

    onComplete({
      topic: selectedTopic,
      selfParty,
      opponentParty,
      objectives,
      customScenario: customScenario || undefined,
      background: generatedBackground || undefined,
      goals,
      issues: issues.filter(i => i.isSelected),
      difficulty,
      era: selectedEra,
    });
  };

  const addObjective = () => {
    if (newObjective.trim() && !objectives.includes(newObjective.trim())) {
      setObjectives([...objectives, newObjective.trim()]);
      setNewObjective('');
    }
  };

  const removeObjective = (index: number) => {
    setObjectives(objectives.filter((_, i) => i !== index));
  };

    // 在 generateBackground 函数附近添加一个生成预设背景的函数
  const getPresetBackground = () => {
        if (!selectedTopic || !selfCountry || !opponentCountry) return null;

        const selfName = countries.find(c => c.id === selfCountry)?.name || selfCountry;
        const opponentName = countries.find(c => c.id === opponentCountry)?.name || opponentCountry;

        return {
            fullBackground: `【背景概述】
本次谈判发生在${ERA_CONFIGS.find(e => e.id === selectedEra)?.name || '当代'}。${selfName}与${opponentName}就「${selectedTopic.name}」议题展开外交磋商。

双方在${selectedTopic.keyIssues?.slice(0, 2).join('、') || '相关领域'}存在分歧，但都表达了通过对话解决问题的意愿。本次会谈旨在寻找互利共赢的解决方案，管控分歧，推动双边关系稳定发展。`,
            background: {
                historicalContext: `${selfName}与${opponentName}的关系源远流长，在多个领域有着广泛的合作与交流。`,
                recentEvents: `近期，双方在${selectedTopic.keyIssues?.[0] || '相关议题'}上出现了一些不同看法。`,
                triggerEvent: `经过多轮工作层面沟通，双方决定举行正式会谈以寻求共识。`,
                currentStance: {
                    self: `${selfName}坚持在平等互利基础上通过对话解决分歧。`,
                    opponent: `${opponentName}表达了通过协商解决问题的意愿。`
                },
                currentSituation: '双方代表团已就位，谈判即将开始。'
            },
            issues: selectedTopic.keyIssues?.map((title, index) => ({
                id: `issue-${index + 1}`,
                title,
                description: `${title}是本次谈判的关键议题之一。`,
                controversy: `双方在${title}上存在一定分歧。`,
                selfPosition: `维护${selfName}的合法利益。`,
                opponentPosition: `寻求对${opponentName}有利的安排。`,
                difficulty: index === 0 ? 'medium' : 'easy',
                importance: 5 - index,
            })) || []
        };
  };

  // 生成背景故事
  const generateBackground = async () => {
    if (!selfCountry || !opponentCountry || !selectedTopic) return;

    setIsGeneratingBackground(true);
    setBackgroundError(null);

    try {
      const selfCountryData = getCountryById(selfCountry) || 
        historicalCountries.find(c => c.id === selfCountry);
      const opponentCountryData = getCountryById(opponentCountry) ||
        historicalCountries.find(c => c.id === opponentCountry);

      const response = await fetch('/api/bilateral-background', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          topic: selectedTopic,
          selfCountry: selfCountryData || { id: selfCountry, name: selfCountry, flag: '', region: '' },
          opponentCountry: opponentCountryData || { id: opponentCountry, name: opponentCountry, flag: '', region: '' },
          era: selectedEra, // 传递历史时期
        })
      });

      const data = await response.json();
      if (data.success && data.data) {
        setGeneratedBackground(data.data);
        // 如果议题还没有设置，使用AI生成的议题
        if (data.data.issues && data.data.issues.length > 0) {
          setIssues(data.data.issues.map((issue: NegotiationIssue, index: number) => ({
            ...issue,
            isSelected: true,
            order: index + 1
          })));
        }
      } else {
        setBackgroundError(data.error || '生成失败');
      }
    } catch (error) {
      console.error('生成背景失败:', error);
      setBackgroundError('网络错误，请重试');
    } finally {
      setIsGeneratingBackground(false);
    }
  };

  // 生成谈判目标（AI自动生成三个方案）
  const generateGoals = async () => {
    if (!selfCountry || !selectedTopic) return;

    setIsGeneratingGoals(true);
    setGoalsError(null);

    try {
      const response = await fetch('/api/generate-goals', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          topic: selectedTopic.name,
          topicDescription: selectedTopic.description || '',
          background: generatedBackground?.fullBackground || '',
          userCountryId: selfCountry,
          opponentCountryIds: opponentCountry ? [opponentCountry] : [],
        })
      });

      const data = await response.json();
      if (data.success && data.goals) {
        const { highGoal, middleGoal, bottomLine } = data.goals;
      
        setHighCaseTitle(highGoal.title);
        setHighCaseDesc(highGoal.description);
        setHighCase(`${highGoal.title}\n\n${highGoal.description}`);
      
        setMiddleCaseTitle(middleGoal.title);
        setMiddleCaseDesc(middleGoal.description);
        setWinWinCase(`${middleGoal.title}\n\n${middleGoal.description}`);
      
        setBottomLineTitle(bottomLine.title);
        setBottomLineDesc(bottomLine.description);
        setBottomLine(`${bottomLine.title}\n\n${bottomLine.description}`);
      
        setAutoGeneratedGoals({
          highCase: `${highGoal.title}\n\n${highGoal.description}`,
          middleCase: `${middleGoal.title}\n\n${middleGoal.description}`,
          bottomLine: `${bottomLine.title}\n\n${bottomLine.description}`,
        });
      } else {
        setGoalsError(data.error || '生成失败');
      }
    } catch (error) {
      console.error('生成目标失败:', error);
      setGoalsError('网络错误，请重试');
    } finally {
      setIsGeneratingGoals(false);
    }
  };

  // 生成谈判方案（进阶模式：生成多个方案供选择）
  const generateProposals = async () => {
    if (!selfCountry || !selectedTopic) return;

    setIsGeneratingProposals(true);
    setProposalsError(null);

    try {
      const response = await fetch('/api/multilateral/proposals', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          topic: selectedTopic.name,
          topicDescription: selectedTopic.description || '',
          background: generatedBackground?.background || '',
          userCountryId: selfCountry,
          opponentCountryIds: opponentCountry ? [opponentCountry] : [],
          difficulty: difficulty,
        })
      });

      const data = await response.json();
      if (data.success && data.proposals) {
        setProposals(data.proposals);
      } else {
        setProposalsError(data.error || '生成失败');
      }
    } catch (error) {
      console.error('生成方案失败:', error);
      setProposalsError('网络错误，请重试');
    } finally {
      setIsGeneratingProposals(false);
    }
  };

  // 切换议题选择
  const toggleIssue = (issueId: string) => {
    setIssues(prev => prev.map(issue => {
      if (issue.id === issueId) {
        const newSelected = !issue.isSelected;
        // 重新排序
        const selectedIssues = prev.filter(i => i.isSelected && i.id !== issueId);
        if (newSelected) {
          selectedIssues.push({ ...issue, isSelected: true, order: selectedIssues.length + 1 });
          return { ...issue, isSelected: true, order: selectedIssues.length + 1 };
        } else {
          // 重新编号
          return { ...issue, isSelected: false, order: undefined };
        }
      }
      return issue;
    }));
    // 重新排序所有选中的议题
    const reordered = issues
      .filter(i => i.isSelected && i.id !== issueId)
      .map((i, idx) => ({ ...i, order: idx + 1 }));
    const unselected = issues.filter(i => !i.isSelected && i.id !== issueId);
    setIssues([...reordered, ...unselected]);
  };

  // 上移议题
  const moveIssueUp = (issueId: string) => {
    const selectedIssues = issues.filter(i => i.isSelected);
    const idx = selectedIssues.findIndex(i => i.id === issueId);
    if (idx > 0) {
      const newOrder = [...selectedIssues];
      [newOrder[idx - 1], newOrder[idx]] = [newOrder[idx], newOrder[idx - 1]];
      // 重新编号
      const reordered = newOrder.map((i, index) => ({ ...i, order: index + 1 }));
      const unselected = issues.filter(i => !i.isSelected);
      setIssues([...reordered, ...unselected]);
    }
  };

  // 下移议题
  const moveIssueDown = (issueId: string) => {
    const selectedIssues = issues.filter(i => i.isSelected);
    const idx = selectedIssues.findIndex(i => i.id === issueId);
    if (idx < selectedIssues.length - 1) {
      const newOrder = [...selectedIssues];
      [newOrder[idx], newOrder[idx + 1]] = [newOrder[idx + 1], newOrder[idx]];
      // 重新编号
      const reordered = newOrder.map((i, index) => ({ ...i, order: index + 1 }));
      const unselected = issues.filter(i => !i.isSelected);
      setIssues([...reordered, ...unselected]);
    }
  };

  return (
    <div className="min-h-screen bg-gradient-to-br from-slate-950 via-slate-900 to-slate-950">
      {/* 背景装饰 */}
      <div className="fixed inset-0 overflow-hidden pointer-events-none">
        <div className="absolute top-1/4 -left-32 w-64 h-64 bg-amber-500/5 rounded-full blur-3xl" />
        <div className="absolute bottom-1/4 -right-32 w-96 h-96 bg-blue-500/5 rounded-full blur-3xl" />
      </div>

      <div className="relative max-w-4xl mx-auto px-6 py-12">
        {/* 标题 */}
        <div className="text-center mb-12">
          <motion.h1
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            className="text-4xl font-bold text-white mb-3"
          >
            谈判场景配置
          </motion.h1>
          <motion.p
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: 0.1 }}
            className="text-slate-400"
          >
            设置谈判参数，AI将为您模拟真实的谈判场景
          </motion.p>
        </div>

        {/* 进度条 */}
        <div className="mb-12">
          <div className="flex justify-between mb-3">
            {steps.map((step, index) => (
              <div
                key={step.key}
                className={`flex items-center gap-2 ${
                  index <= currentStepIndex ? 'text-amber-400' : 'text-slate-500'
                }`}
              >
                <div
                  className={`w-8 h-8 rounded-full flex items-center justify-center text-sm font-medium ${
                    index < currentStepIndex
                      ? 'bg-amber-500 text-white'
                      : index === currentStepIndex
                      ? 'bg-amber-500/20 border-2 border-amber-500 text-amber-400'
                      : 'bg-slate-800 text-slate-500'
                  }`}
                >
                  {index < currentStepIndex ? (
                    <svg className="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M5 13l4 4L19 7" />
                    </svg>
                  ) : (
                    index + 1
                  )}
                </div>
                <span className="text-sm hidden sm:block">{step.label}</span>
              </div>
            ))}
          </div>
          <div className="h-1 bg-slate-800 rounded-full overflow-hidden">
            <motion.div
              initial={{ width: '0%' }}
              animate={{ width: `${((currentStepIndex + 1) / steps.length) * 100}%` }}
              className="h-full bg-gradient-to-r from-amber-500 to-amber-400"
            />
          </div>
        </div>

        {/* 步骤内容 */}
        <AnimatePresence mode="wait">
          {/* 步骤1: 选择主题 */}
          {currentStep === 'topic' && (
            <motion.div
              key="topic"
              initial={{ opacity: 0, x: 20 }}
              animate={{ opacity: 1, x: 0 }}
              exit={{ opacity: 0, x: -20 }}
              className="space-y-6"
            >
              <div className="text-center mb-8">
                <h2 className="text-xl font-semibold text-white mb-2">选择谈判主题</h2>
                <p className="text-sm text-slate-500">选择一个您想要练习的谈判场景</p>
              </div>

              {/* 筛选器 */}
              <div className="flex flex-wrap justify-center gap-2 mb-6">
                <button
                  onClick={() => setTopicFilter('all')}
                  className={`px-4 py-2 rounded-lg text-sm font-medium transition-all ${
                    topicFilter === 'all'
                      ? 'bg-amber-500 text-white'
                      : 'bg-slate-800 text-slate-400 hover:text-white hover:bg-slate-700'
                  }`}
                >
                  全部
                </button>
                <button
                  onClick={() => setTopicFilter('modern')}
                  className={`px-4 py-2 rounded-lg text-sm font-medium transition-all flex items-center gap-1.5 ${
                    topicFilter === 'modern'
                      ? 'bg-amber-500 text-white'
                      : 'bg-slate-800 text-slate-400 hover:text-white hover:bg-slate-700'
                  }`}
                >
                  <Globe className="w-4 h-4" />
                  现代议题
                </button>
                <button
                  onClick={() => setTopicFilter('cold-war')}
                  className={`px-4 py-2 rounded-lg text-sm font-medium transition-all flex items-center gap-1.5 ${
                    topicFilter === 'cold-war'
                      ? 'bg-red-600 text-white'
                      : 'bg-slate-800 text-slate-400 hover:text-white hover:bg-slate-700'
                  }`}
                >
                  <Clock className="w-4 h-4" />
                  历史场景
                </button>
                <button
                  onClick={() => setTopicFilter('future')}
                  className={`px-4 py-2 rounded-lg text-sm font-medium transition-all flex items-center gap-1.5 ${
                    topicFilter === 'future'
                      ? 'bg-gradient-to-r from-purple-500 to-pink-500 text-white'
                      : 'bg-slate-800 text-slate-400 hover:text-white hover:bg-slate-700'
                  }`}
                >
                  <Rocket className="w-4 h-4" />
                  未来议题
                </button>
              </div>

              {/* 未来议题类别筛选 */}
              {topicFilter === 'future' && (
                <div className="flex flex-wrap justify-center gap-2 mb-6">
                  <button
                    onClick={() => setSelectedFutureCategory('all')}
                    className={`px-3 py-1.5 rounded-lg text-xs font-medium transition-all ${
                      selectedFutureCategory === 'all'
                        ? 'bg-purple-500/30 text-purple-300 border border-purple-500/50'
                        : 'bg-slate-800/50 text-slate-400 hover:text-white'
                    }`}
                  >
                    全部
                  </button>
                  {futureCategories.map((cat) => (
                    <button
                      key={cat.id}
                      onClick={() => setSelectedFutureCategory(cat.id)}
                      className={`px-3 py-1.5 rounded-lg text-xs font-medium transition-all flex items-center gap-1 ${
                        selectedFutureCategory === cat.id
                          ? 'bg-slate-700 text-white border border-slate-500'
                          : 'bg-slate-800/50 text-slate-400 hover:text-white'
                      }`}
                    >
                      <span>{cat.icon}</span>
                      {cat.name}
                    </button>
                  ))}
                </div>
              )}

              <div className="grid gap-4">
                {/* 现代议题 */}
                {(topicFilter === 'all' || topicFilter === 'modern') && negotiationTopics
                  .filter(t => topicFilter === 'all' || t.era === 'modern')
                  .map((topic) => (
                    <div key={topic.id} className="space-y-2">
                      <button
                        onClick={() => setSelectedTopic(topic)}
                        className={`w-full p-5 rounded-2xl text-left transition-all ${
                          selectedTopic?.id === topic.id
                            ? 'bg-amber-500/20 border-2 border-amber-500'
                            : 'bg-slate-900/50 border border-slate-700/50 hover:border-slate-600'
                        }`}
                      >
                        <div className="flex items-start gap-4">
                          <div
                            className={`w-12 h-12 rounded-xl flex items-center justify-center flex-shrink-0 ${
                              selectedTopic?.id === topic.id ? 'bg-amber-500/30' : 'bg-slate-800'
                            }`}
                          >
                            {topic.category === 'trade' && (
                              <svg className="w-6 h-6 text-amber-400" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M3 3h2l.4 2M7 13h10l4-8H5.4M7 13L5.4 5M7 13l-2.293 2.293c-.63.63-.184 1.707.707 1.707H17m0 0a2 2 0 100 4 2 2 0 000-4zm-8 2a2 2 0 11-4 0 2 2 0 014 0z" />
                              </svg>
                            )}
                            {topic.category === 'territory' && (
                              <svg className="w-6 h-6 text-blue-400" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M3.055 11H5a2 2 0 012 2v1a2 2 0 002 2 2 2 0 012 2v2.945M8 3.935V5.5A2.5 2.5 0 0010.5 8h.5a2 2 0 012 2 2 2 0 104 0 2 2 0 012-2h1.064M15 20.488V18a2 2 0 012-2h3.064M21 12a9 9 0 11-18 0 9 9 0 0118 0z" />
                              </svg>
                            )}
                            {topic.category === 'peace' && (
                              <svg className="w-6 h-6 text-green-400" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 12l2 2 4-4m5.618-4.016A11.955 11.955 0 0112 2.944a11.955 11.955 0 01-8.618 3.04A12.02 12.02 0 003 9c0 5.591 3.824 10.29 9 11.622 5.176-1.332 9-6.03 9-11.622 0-1.042-.133-2.052-.382-3.016z" />
                              </svg>
                            )}
                            {topic.category === 'security' && (
                              <svg className="w-6 h-6 text-red-400" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 15v2m-6 4h12a2 2 0 002-2v-6a2 2 0 00-2-2H6a2 2 0 00-2 2v6a2 2 0 002 2zm10-10V7a4 4 0 00-8 0v4h8z" />
                              </svg>
                            )}
                            {topic.category === 'environmental' && (
                              <svg className="w-6 h-6 text-emerald-400" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M3.055 11H5a2 2 0 012 2v1a2 2 0 002 2 2 2 0 012 2v2.945M8 3.935V5.5A2.5 2.5 0 0010.5 8h.5a2 2 0 012 2 2 2 0 104 0 2 2 0 012-2h1.064M15 20.488V18a2 2 0 012-2h3.064M21 12a9 9 0 11-18 0 9 9 0 0118 0z" />
                              </svg>
                            )}
                            {topic.category === 'cultural' && (
                              <svg className="w-6 h-6 text-purple-400" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 6.253v13m0-13C10.832 5.477 9.246 5 7.5 5S4.168 5.477 3 6.253v13C4.168 18.477 5.754 18 7.5 18s3.332.477 4.5 1.253m0-13C13.168 5.477 14.754 5 16.5 5c1.747 0 3.332.477 4.5 1.253v13C19.832 18.477 18.247 18 16.5 18c-1.746 0-3.332.477-4.5 1.253" />
                              </svg>
                            )}
                          </div>
                          <div className="flex-1 min-w-0">
                            <div className="flex items-center gap-2 flex-wrap mb-1">
                              <h3 className="text-base font-medium text-white">{topic.name}</h3>
                              {topic.era === 'cold-war' && (
                                <span className="px-2 py-0.5 bg-red-500/20 text-red-400 text-xs rounded-full flex items-center gap-1">
                                  <Clock className="w-3 h-3" />
                                  历史
                                </span>
                              )}
                            </div>
                            <p className="text-sm text-slate-400 mb-2">{topic.description}</p>
                            <div className="flex flex-wrap gap-1">
                              {topic.keyIssues.slice(0, 3).map((issue: string) => (
                                <span
                                  key={issue}
                                  className="px-2 py-0.5 bg-slate-800 text-slate-400 text-xs rounded"
                                >
                                  {issue}
                                </span>
                              ))}
                            </div>
                          </div>
                        </div>
                      </button>
                      
                      {/* 展开详情 */}
                      {selectedTopic?.id === topic.id && topic.background && (
                        <motion.div
                          initial={{ opacity: 0, height: 0 }}
                          animate={{ opacity: 1, height: 'auto' }}
                          exit={{ opacity: 0, height: 0 }}
                          className="bg-slate-800/50 rounded-xl p-4 border border-slate-700/50"
                        >
                          <div className="prose prose-invert prose-sm max-w-none">
                            <div className="text-slate-300 whitespace-pre-line text-sm leading-relaxed">
                              {topic.background}
                            </div>
                          </div>
                        </motion.div>
                      )}
                    </div>
                  ))}

                {/* 历史场景议题 */}
                {topicFilter === 'cold-war' && coldWarTopics.map((topic) => (
                  <div key={topic.id} className="space-y-2">
                    <button
                      onClick={() => setSelectedTopic(topic)}
                      className={`w-full p-5 rounded-2xl text-left transition-all ${
                        selectedTopic?.id === topic.id
                          ? 'bg-red-500/20 border-2 border-red-500'
                          : 'bg-slate-900/50 border border-slate-700/50 hover:border-slate-600'
                      }`}
                    >
                      <div className="flex items-start gap-4">
                        <div
                          className={`w-12 h-12 rounded-xl flex items-center justify-center flex-shrink-0 ${
                            selectedTopic?.id === topic.id ? 'bg-red-500/30' : 'bg-red-900/30'
                          }`}
                        >
                          {topic.category === 'trade' && (
                            <svg className="w-6 h-6 text-red-400" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M3 3h2l.4 2M7 13h10l4-8H5.4M7 13L5.4 5M7 13l-2.293 2.293c-.63.63-.184 1.707.707 1.707H17m0 0a2 2 0 100 4 2 2 0 000-4zm-8 2a2 2 0 11-4 0 2 2 0 014 0z" />
                            </svg>
                          )}
                          {topic.category === 'security' && (
                            <svg className="w-6 h-6 text-red-400" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 15v2m-6 4h12a2 2 0 002-2v-6a2 2 0 00-2-2H6a2 2 0 00-2 2v6a2 2 0 002 2zm10-10V7a4 4 0 00-8 0v4h8z" />
                            </svg>
                          )}
                          {topic.category === 'diplomatic' && (
                            <svg className="w-6 h-6 text-red-400" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M21 12a9 9 0 01-9 9m9-9a9 9 0 00-9-9m9 9H3m9 9a9 9 0 01-9-9m9 9c1.657 0 3-4.03 3-9s-1.343-9-3-9m0 18c-1.657 0-3-4.03-3-9s1.343-9 3-9m-9 9a9 9 0 019-9" />
                            </svg>
                          )}
                          {topic.category === 'technology' && (
                            <svg className="w-6 h-6 text-red-400" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M13 10V3L4 14h7v7l9-11h-7z" />
                            </svg>
                          )}
                          {topic.category === 'propaganda' && (
                            <svg className="w-6 h-6 text-red-400" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M11.049 2.927c.3-.921 1.603-.921 1.902 0l1.519 4.674a1 1 0 00.95.69h4.915c.969 0 1.371 1.24.588 1.81l-3.976 2.888a1 1 0 00-.363 1.118l1.518 4.674c.3.922-.755 1.688-1.538 1.118l-3.976-2.888a1 1 0 00-1.176 0l-3.976 2.888c-.783.57-1.838-.197-1.538-1.118l1.518-4.674a1 1 0 00-.363-1.118l-3.976-2.888c-.784-.57-.38-1.81.588-1.81h4.914a1 1 0 00.951-.69l1.519-4.674z" />
                            </svg>
                          )}
                          {topic.category === 'territory' && (
                            <svg className="w-6 h-6 text-red-400" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M3.055 11H5a2 2 0 012 2v1a2 2 0 002 2 2 2 0 012 2v2.945M8 3.935V5.5A2.5 2.5 0 0010.5 8h.5a2 2 0 012 2 2 2 0 104 0 2 2 0 012-2h1.064M15 20.488V18a2 2 0 012-2h3.064M21 12a9 9 0 11-18 0 9 9 0 0118 0z" />
                            </svg>
                          )}
                          {topic.category === 'peace' && (
                            <svg className="w-6 h-6 text-red-400" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 12l2 2 4-4m5.618-4.016A11.955 11.955 0 0112 2.944a11.955 11.955 0 01-8.618 3.04A12.02 12.02 0 003 9c0 5.591 3.824 10.29 9 11.622 5.176-1.332 9-6.03 9-11.622 0-1.042-.133-2.052-.382-3.016z" />
                            </svg>
                          )}
                        </div>
                        <div className="flex-1 min-w-0">
                          <div className="flex items-center gap-2 flex-wrap mb-1">
                            <h3 className="text-base font-medium text-white">{topic.name}</h3>
                            <span className="px-2 py-0.5 bg-red-500/20 text-red-400 text-xs rounded-full flex items-center gap-1">
                              <Clock className="w-3 h-3" />
                              冷战历史
                            </span>
                          </div>
                          <p className="text-sm text-slate-400 mb-2">{topic.description}</p>
                          <div className="flex flex-wrap gap-1">
                            {topic.keyIssues.slice(0, 3).map((issue: string) => (
                              <span
                                key={issue}
                                className="px-2 py-0.5 bg-slate-800 text-slate-400 text-xs rounded"
                              >
                                {issue}
                              </span>
                            ))}
                          </div>
                        </div>
                      </div>
                    </button>
                    
                    {/* 展开详情 */}
                    {selectedTopic?.id === topic.id && topic.background && (
                      <motion.div
                        initial={{ opacity: 0, height: 0 }}
                        animate={{ opacity: 1, height: 'auto' }}
                        exit={{ opacity: 0, height: 0 }}
                        className="bg-slate-800/50 rounded-xl p-4 border border-slate-700/50"
                      >
                        <div className="prose prose-invert prose-sm max-w-none">
                          <div className="text-slate-300 whitespace-pre-line text-sm leading-relaxed">
                            {topic.background}
                          </div>
                        </div>
                      </motion.div>
                    )}
                  </div>
                ))}

              </div>

              {/* 未来议题列表 */}
              {(topicFilter === 'all' || topicFilter === 'future') && (
                <div className="space-y-6">
                  {topicFilter === 'future' && (
                    <div className="text-center py-4">
                      <div className="inline-flex items-center gap-2 px-4 py-2 bg-gradient-to-r from-purple-500/20 to-pink-500/20 rounded-full text-purple-300 text-sm">
                        <Rocket className="w-4 h-4" />
                        探索未来可能面临的全球挑战
                      </div>
                    </div>
                  )}
                  <div className="grid gap-4">
                    {futureTopics
                      .filter(t => selectedFutureCategory === 'all' || t.category === selectedFutureCategory)
                      .map((topic) => (
                        <button
                          key={topic.id}
                          onClick={() => setSelectedTopic(topic)}
                          className={`p-5 rounded-2xl text-left transition-all ${
                            selectedTopic?.id === topic.id
                              ? 'bg-gradient-to-r from-purple-500/20 to-pink-500/20 border-2 border-purple-500'
                              : 'bg-slate-900/50 border border-slate-700/50 hover:border-purple-500/50'
                          }`}
                        >
                          <div className="flex items-start gap-4">
                            <div
                              className={`w-12 h-12 rounded-xl flex items-center justify-center text-2xl ${
                                selectedTopic?.id === topic.id ? 'bg-purple-500/30' : 'bg-slate-800'
                              }`}
                            >
                              {futureCategories.find(c => c.id === topic.category)?.icon || '🔮'}
                            </div>
                            <div className="flex-1">
                              <div className="flex items-center gap-2 mb-1">
                                <h3 className="text-base font-medium text-white">{topic.name}</h3>
                                {topicFilter === 'all' && (
                                  <span className="px-2 py-0.5 bg-purple-500/20 text-purple-400 text-xs rounded-full">未来</span>
                                )}
                              </div>
                              <p className="text-sm text-slate-400 mb-2">{topic.description}</p>
                              <div className="flex flex-wrap gap-1">
                                {topic.keyIssues.slice(0, 3).map((issue: string) => (
                                  <span
                                    key={issue}
                                    className="px-2 py-0.5 bg-slate-800 text-slate-400 text-xs rounded"
                                  >
                                    {issue}
                                  </span>
                                ))}
                              </div>
                            </div>
                          </div>
                        </button>
                      ))}
                  </div>
                </div>
              )}

              {/* 自定义场景选项 */}
              <div className="mt-6 pt-6 border-t border-slate-700/50">
                <div className="text-center mb-4">
                  <p className="text-sm text-slate-500 mb-3">或者创建自定义场景</p>
                  <button
                    onClick={() => setShowCustomUploader(true)}
                    className={`inline-flex items-center gap-2 px-6 py-3 rounded-xl transition-all ${
                      customScenario
                        ? 'bg-gradient-to-r from-purple-500 to-pink-500 text-white'
                        : 'bg-slate-800/50 border border-dashed border-purple-500/50 text-purple-400 hover:border-purple-500 hover:bg-purple-500/10'
                    }`}
                  >
                    {customScenario ? (
                      <>
                        <Check className="w-5 h-5" />
                        已选择: {customScenario.title}
                      </>
                    ) : (
                      <>
                        <Sparkles className="w-5 h-5" />
                        上传自定义场景
                      </>
                    )}
                  </button>
                </div>
              </div>

              {/* 自定义场景上传模态框 */}
              <AnimatePresence>
                {showCustomUploader && (
                  <motion.div
                    initial={{ opacity: 0 }}
                    animate={{ opacity: 1 }}
                    exit={{ opacity: 0 }}
                    className="fixed inset-0 bg-black/60 backdrop-blur-sm flex items-center justify-center z-50 p-4"
                    onClick={() => setShowCustomUploader(false)}
                  >
                    <motion.div
                      initial={{ scale: 0.95, opacity: 0 }}
                      animate={{ scale: 1, opacity: 1 }}
                      exit={{ scale: 0.95, opacity: 0 }}
                      onClick={(e) => e.stopPropagation()}
                    >
                      <CustomScenarioUploader
                        onUpload={(scenario) => {
                          setCustomScenario(scenario);
                          setSelectedTopic({
                            id: 'custom-' + Date.now(),
                            name: scenario.title,
                            category: 'trade' as const,
                            description: scenario.description,
                            keyIssues: scenario.keyIssues,
                          });
                          setShowCustomUploader(false);
                        }}
                        onCancel={() => setShowCustomUploader(false)}
                      />
                    </motion.div>
                  </motion.div>
                )}
              </AnimatePresence>
            </motion.div>
          )}

          {/* 步骤2: 选择参与方 */}
          {currentStep === 'parties' && (
            <motion.div
              key="parties"
              initial={{ opacity: 0, x: 20 }}
              animate={{ opacity: 1, x: 0 }}
              exit={{ opacity: 0, x: -20 }}
              className="space-y-8"
            >
              {/* 己方 */}
              <div className="bg-slate-900/50 rounded-2xl border border-slate-700/50 p-6">
                <h3 className="text-lg font-medium text-white mb-4 flex items-center gap-2">
                  <span className="w-8 h-8 rounded-full bg-amber-500/20 flex items-center justify-center text-amber-400">
                    我
                  </span>
                  选择己方代表
                </h3>
                {/* 时期筛选 */}
                <div className="flex flex-wrap gap-2 mb-4">
                  <button
                    onClick={() => {}}
                    className={`px-3 py-1.5 rounded-lg text-xs font-medium ${
                      topicFilter === 'all' || topicFilter === 'modern'
                        ? 'bg-amber-500/20 text-amber-400 border border-amber-500/50'
                        : 'bg-slate-800/50 text-slate-400 border border-transparent'
                    }`}
                  >
                    现代国家
                  </button>
                  {selectedTopic?.era === 'cold-war' && (
                    <button
                      onClick={() => {}}
                      className="px-3 py-1.5 rounded-lg text-xs font-medium bg-red-500/20 text-red-400 border border-red-500/50 flex items-center gap-1"
                    >
                      <Clock className="w-3 h-3" />
                      冷战时期
                    </button>
                  )}
                </div>
                <div className="grid grid-cols-2 sm:grid-cols-3 gap-3">
                                  {/* 根据议题时代优先判断，若议题有时代属性则优先用议题的，否则用选择的时期 */}
                                  {(() => {
                                      const effectiveEra = selectedTopic?.era || selectedEra;

                                      if (effectiveEra === 'future') {
                                          return futureCountries.map((country) => (
                                              <button
                                                  key={country.id}
                                                  onClick={() => setSelfCountry(country.id)}
                                                  className={`p-3 rounded-xl text-left transition-all ${selfCountry === country.id
                                                          ? 'bg-amber-500/20 border border-amber-500'
                                                          : 'bg-slate-800/50 border border-slate-700/50 hover:border-slate-600'
                                                      }`}
                                              >
                                                  <span className="text-xl mr-2">{country.flag}</span>
                                                  <span className="text-sm text-slate-300">{country.name}</span>
                                              </button>
                                          ));
                                      }

                                      if (effectiveEra?.startsWith('cold-war')) {
                                          return historicalCountries
                                              .filter(c => c.era === 'cold-war')
                                              .map((country) => (
                                                  <button
                                                      key={country.id}
                                                      onClick={() => setSelfCountry(country.id)}
                                                      className={`p-3 rounded-xl text-left transition-all ${selfCountry === country.id
                                                              ? 'bg-amber-500/20 border border-amber-500'
                                                              : 'bg-slate-800/50 border border-slate-700/50 hover:border-slate-600'
                                                          }`}
                                                  >
                                                      <span className="text-xl mr-2">{country.flag}</span>
                                                      <div>
                                                          <span className="text-sm text-slate-300 block">{country.name}</span>
                                                          <span className="text-xs text-slate-500">{country.existedUntil ? `至${country.existedUntil}` : '历史国家'}</span>
                                                      </div>
                                                  </button>
                                              ));
                                      }

                                      // 默认显示现代国家（包括 modern / post-cold-war / post-2008 等当代时期）
                                      return countries.map((country) => (
                                          <button
                                              key={country.id}
                                              onClick={() => setSelfCountry(country.id)}
                                              className={`p-3 rounded-xl text-left transition-all ${selfCountry === country.id
                                                      ? 'bg-amber-500/20 border border-amber-500'
                                                      : 'bg-slate-800/50 border border-slate-700/50 hover:border-slate-600'
                                                  }`}
                                          >
                                              <span className="text-xl mr-2">{country.flag}</span>
                                              <span className="text-sm text-slate-300">{country.name}</span>
                                          </button>
                                      ));
                                  })()}
                </div>
              </div>

              {/* 对方 */}
              <div className="bg-slate-900/50 rounded-2xl border border-slate-700/50 p-6">
                <h3 className="text-lg font-medium text-white mb-4 flex items-center gap-2">
                  <span className="w-8 h-8 rounded-full bg-red-500/20 flex items-center justify-center text-red-400">
                    对方
                  </span>
                  选择对方代表
                </h3>
                <div className="grid grid-cols-2 sm:grid-cols-3 gap-3 mb-6">
                                  {/* 根据议题时代优先判断，若议题有时代属性则优先用议题的，否则用选择的时期 */}
                                  {(() => {
                                      const effectiveEra = selectedTopic?.era || selectedEra;

                                      if (effectiveEra === 'future') {
                                          return futureCountries.map((country) => (
                                              <button
                                                  key={country.id}
                                                  disabled={country.id === selfCountry}
                                                  onClick={() => setOpponentCountry(country.id)}
                                                  className={`p-3 rounded-xl text-left transition-all ${opponentCountry === country.id
                                                          ? 'bg-amber-500/20 border border-amber-500'
                                                          : 'bg-slate-800/50 border border-slate-700/50 hover:border-slate-600'
                                                      }`}
                                              >
                                                  <span className="text-xl mr-2">{country.flag}</span>
                                                  <span className="text-sm text-slate-300">{country.name}</span>
                                              </button>
                                          ));
                                      }

                                      if (effectiveEra?.startsWith('cold-war')) {
                                          return historicalCountries
                                              .filter(c => c.era === 'cold-war')
                                              .map((country) => (
                                                  <button
                                                      key={country.id}
                                                      onClick={() => setOpponentCountry(country.id)}
                                                      disabled={country.id === selfCountry}
                                                      className={`p-3 rounded-xl text-left transition-all ${opponentCountry === country.id
                                                              ? 'bg-amber-500/20 border border-amber-500'
                                                              : 'bg-slate-800/50 border border-slate-700/50 hover:border-slate-600'
                                                          }`}
                                                  >
                                                      <span className="text-xl mr-2">{country.flag}</span>
                                                      <div>
                                                          <span className="text-sm text-slate-300 block">{country.name}</span>
                                                          <span className="text-xs text-slate-500">{country.existedUntil ? `至${country.existedUntil}` : '历史国家'}</span>
                                                      </div>
                                                  </button>
                                              ));
                                      }

                                      // 默认显示现代国家（包括 modern / post-cold-war / post-2008 等当代时期）
                                      return countries.map((country) => (
                                          <button
                                              key={country.id}
                                              onClick={() => setOpponentCountry(country.id)}
                                              disabled={country.id === selfCountry}
                                              className={`p-3 rounded-xl text-left transition-all ${opponentCountry === country.id
                                                      ? 'bg-amber-500/20 border border-amber-500'
                                                      : 'bg-slate-800/50 border border-slate-700/50 hover:border-slate-600'
                                                  }`}
                                          >
                                              <span className="text-xl mr-2">{country.flag}</span>
                                              <span className="text-sm text-slate-300">{country.name}</span>
                                          </button>
                                      ));
                                  })()}
                </div>

                {/* 性格预设 */}
                <div>
                  <p className="text-sm text-slate-400 mb-3">选择对方谈判风格（可选）</p>
                  <div className="flex flex-wrap gap-2">
                    {personalityPresets.map((preset) => (
                      <button
                        key={preset.name}
                        onClick={() => setOpponentPersonality(preset.name)}
                        className={`px-4 py-2 rounded-xl text-sm transition-all ${
                          opponentPersonality === preset.name
                            ? 'bg-blue-500/20 border border-blue-500 text-blue-400'
                            : 'bg-slate-800/50 border border-slate-700/50 text-slate-400 hover:border-slate-600'
                        }`}
                      >
                        {preset.name}
                      </button>
                    ))}
                  </div>
                </div>
              </div>
            </motion.div>
          )}

          {/* 步骤4: 历史时期选择 */}
          {currentStep === 'era' && (
            <motion.div
              key="era"
              initial={{ opacity: 0, x: 20 }}
              animate={{ opacity: 1, x: 0 }}
              exit={{ opacity: 0, x: -20 }}
              className="space-y-6"
            >
              <div className="text-center mb-8">
                <h2 className="text-xl font-semibold text-white mb-2 flex items-center justify-center gap-2">
                  <Clock className="w-5 h-5 text-amber-400" />
                  选择历史时期
                </h2>
                <p className="text-sm text-slate-500">
                  选择不同的历史时期将影响谈判风格、语言表达和议题背景
                </p>
              </div>

              <div className="grid gap-4">
                {ERA_CONFIGS.map((era) => (
                  <button
                    key={era.id}
                    onClick={() => setSelectedEra(era.id as HistoricalEra)}
                    className={`p-6 rounded-2xl border-2 text-left transition-all ${
                      selectedEra === era.id
                        ? 'bg-amber-500/10 border-amber-500'
                        : 'bg-slate-900/50 border-slate-700/50 hover:border-slate-600'
                    }`}
                  >
                    <div className="flex items-start gap-4">
                      <div className={`w-12 h-12 rounded-xl flex items-center justify-center text-2xl ${
                        selectedEra === era.id ? 'bg-amber-500/20' : 'bg-slate-800'
                      }`}>
                        {era.id === 'cold-war-early' ? '⚔️' :
                         era.id === 'cold-war-detente' ? '🕊️' :
                         era.id === 'cold-war-late' ? '🔄' :
                         era.id === 'post-cold-war' ? '🌐' :
                         era.id === 'post-2008' ? '📉' : '🏛️'}
                      </div>
                      <div className="flex-1">
                        <div className="flex items-center justify-between mb-2">
                          <h3 className={`text-lg font-semibold ${
                            selectedEra === era.id ? 'text-amber-400' : 'text-white'
                          }`}>
                            {era.name}
                          </h3>
                          <span className="text-sm text-slate-500 bg-slate-800 px-2 py-1 rounded">
                            {era.shortName}
                          </span>
                          {selectedEra === era.id && (
                            <span className="flex items-center gap-1 text-xs text-amber-400">
                              <Check className="w-4 h-4" />
                              已选择
                            </span>
                          )}
                        </div>
                        <p className="text-sm text-slate-400 mb-3">{era.description}</p>
                        
                        {/* 时期特征标签 */}
                        <div className="flex flex-wrap gap-2">
                          {era.characteristics.slice(0, 3).map((char, idx) => (
                            <span
                              key={idx}
                              className={`px-2 py-0.5 text-xs rounded-full ${
                                selectedEra === era.id
                                  ? 'bg-amber-500/20 text-amber-400'
                                  : 'bg-slate-800 text-slate-400'
                              }`}
                            >
                              {char}
                            </span>
                          ))}
                        </div>

                        {/* 语言风格提示 */}
                        <div className={`mt-3 text-xs ${selectedEra === era.id ? 'text-amber-300' : 'text-slate-500'}`}>
                          语言风格：{era.typicalLanguageStyle}
                        </div>
                      </div>
                    </div>
                  </button>
                ))}
              </div>

              {/* 时期提示 */}
              <div className="bg-slate-800/50 rounded-xl p-4 mt-4">
                <h4 className="text-sm font-medium text-slate-300 mb-2">时期影响说明</h4>
                <ul className="text-xs text-slate-400 space-y-1">
                  <li>• 不同历史时期的<span className="text-amber-400">外交语言风格</span>会有明显差异</li>
                  <li>• 各国谈判立场和策略会受时期背景影响</li>
                  <li>• 议题设置和争议焦点将反映时代特点</li>
                  <li>• 建议新手选择<span className="text-green-400">当代</span>时期，语言表达更易理解</li>
                </ul>
              </div>
            </motion.div>
          )}

          {/* 步骤5: 背景故事 */}
          {currentStep === 'background' && (
            <motion.div
              key="background"
              initial={{ opacity: 0, x: 20 }}
              animate={{ opacity: 1, x: 0 }}
              exit={{ opacity: 0, x: -20 }}
              className="space-y-6"
            >
              <div className="text-center mb-8">
                <h2 className="text-xl font-semibold text-white mb-2 flex items-center justify-center gap-2">
                  <BookOpen className="w-5 h-5 text-amber-400" />
                  谈判背景故事
                </h2>
                <p className="text-sm text-slate-500">
                  AI将根据您选择的国家和主题，生成逼真的谈判背景
                </p>
              </div>

              {/* 背景预览区域 */}
              {generatedBackground ? (
                <motion.div
                  initial={{ opacity: 0, y: 20 }}
                  animate={{ opacity: 1, y: 0 }}
                  className="space-y-6"
                >
                  {/* 完整背景故事 */}
                  <div className="bg-slate-900/50 rounded-2xl border border-slate-700/50 p-6">
                    <h3 className="text-lg font-medium text-amber-400 mb-4">背景故事</h3>
                    <div className="prose prose-invert prose-sm max-w-none">
                      <div className="text-slate-300 whitespace-pre-line leading-relaxed">
                        {generatedBackground.fullBackground}
                      </div>
                    </div>
                  </div>

                  {/* 关键要素 */}
                  <div className="grid gap-4">
                    {generatedBackground.background.historicalContext && (
                      <div className="bg-slate-900/50 rounded-xl border border-slate-700/50 p-4">
                        <h4 className="text-sm font-medium text-purple-400 mb-2">历史渊源</h4>
                        <p className="text-sm text-slate-300">{generatedBackground.background.historicalContext}</p>
                      </div>
                    )}
                    {generatedBackground.background.triggerEvent && (
                      <div className="bg-red-900/20 rounded-xl border border-red-700/30 p-4">
                        <h4 className="text-sm font-medium text-red-400 mb-2">直接导火索</h4>
                        <p className="text-sm text-slate-300">{generatedBackground.background.triggerEvent}</p>
                      </div>
                    )}
                    {generatedBackground.background.recentEvents && (
                      <div className="bg-blue-900/20 rounded-xl border border-blue-700/30 p-4">
                        <h4 className="text-sm font-medium text-blue-400 mb-2">近期发展</h4>
                        <p className="text-sm text-slate-300">{generatedBackground.background.recentEvents}</p>
                      </div>
                    )}
                  </div>

                  {/* 双方立场对比 */}
                  <div className="grid md:grid-cols-2 gap-4">
                    <div className="bg-amber-900/20 rounded-xl border border-amber-700/30 p-4">
                      <h4 className="text-sm font-medium text-amber-400 mb-2 flex items-center gap-2">
                        <span>{countries.find(c => c.id === selfCountry)?.flag || '🏳️'}</span>
                        己方立场
                      </h4>
                      <p className="text-sm text-slate-300">{generatedBackground.background.currentStance.self}</p>
                    </div>
                    <div className="bg-red-900/20 rounded-xl border border-red-700/30 p-4">
                      <h4 className="text-sm font-medium text-red-400 mb-2 flex items-center gap-2">
                        <span>{countries.find(c => c.id === opponentCountry)?.flag || '🏳️'}</span>
                        对方立场
                      </h4>
                      <p className="text-sm text-slate-300">{generatedBackground.background.currentStance.opponent}</p>
                    </div>
                  </div>

                  {/* 重新生成按钮 */}
                  <div className="flex justify-center">
                    <button
                      onClick={generateBackground}
                      disabled={isGeneratingBackground}
                      className="px-6 py-3 bg-slate-800 hover:bg-slate-700 disabled:opacity-50 text-slate-300 rounded-xl transition-colors flex items-center gap-2"
                    >
                      {isGeneratingBackground ? (
                        <>
                          <Loader2 className="w-4 h-4 animate-spin" />
                          生成中...
                        </>
                      ) : (
                        <>
                          <RefreshCw className="w-4 h-4" />
                          重新生成
                        </>
                      )}
                    </button>
                  </div>
                </motion.div>
              ) : (
                <div className="text-center py-12">
                  {isGeneratingBackground ? (
                    <div className="space-y-4">
                      <Loader2 className="w-12 h-12 mx-auto text-amber-400 animate-spin" />
                      <p className="text-slate-400">正在生成背景故事...</p>
                      <p className="text-sm text-slate-500">这可能需要几秒钟时间</p>
                    </div>
                  ) : backgroundError ? (
                    <div className="space-y-4">
                      <AlertCircle className="w-12 h-12 mx-auto text-red-400" />
                      <p className="text-red-400">{backgroundError}</p>
                      <button
                        onClick={generateBackground}
                        className="px-6 py-3 bg-amber-600 hover:bg-amber-500 text-white rounded-xl transition-colors"
                      >
                        重试
                      </button>
                    </div>
                  ) : (
                    <div className="space-y-4">
                      <BookOpen className="w-12 h-12 mx-auto text-slate-500" />
                      <p className="text-slate-400">点击下方按钮生成背景故事</p>
                      <p className="text-sm text-slate-500">
                        背景将包含历史渊源、导火索事件和双方立场
                      </p>
                      <button
                        onClick={generateBackground}
                        className="px-8 py-4 bg-gradient-to-r from-amber-500 to-amber-600 hover:from-amber-400 hover:to-amber-500 text-white rounded-xl transition-all flex items-center gap-2 mx-auto shadow-lg shadow-amber-500/25"
                      >
                        <Sparkles className="w-5 h-5" />
                        AI生成背景故事
                      </button>
                    </div>
                  )}
                </div>
              )}
            </motion.div>
          )}

          {/* 步骤5: 设定目标 */}
          {currentStep === 'goals' && (
  <motion.div
    key="goals"
    initial={{ opacity: 0, x: 20 }}
    animate={{ opacity: 1, x: 0 }}
    exit={{ opacity: 0, x: -20 }}
    className="space-y-8"
  >
    <div className="text-center mb-6">
      <h2 className="text-xl font-semibold text-white mb-2 flex items-center justify-center gap-2">
        <Target className="w-5 h-5 text-amber-400" />
        设定谈判目标
      </h2>
      <p className="text-sm text-slate-500">
        AI 将根据您的国家和议题自动生成三个方案，您可以编辑调整
      </p>
    </div>

    {!autoGeneratedGoals ? (
      <div className="space-y-6">
        {/* 说明卡片 */}
        <div className="bg-slate-900/50 rounded-2xl border border-slate-700/50 p-6">
          <div className="flex items-start gap-3">
            <div className="w-10 h-10 rounded-full bg-amber-500/20 flex items-center justify-center flex-shrink-0">
              <Sparkles className="w-5 h-5 text-amber-400" />
            </div>
            <div>
              <h4 className="text-white font-medium mb-2">什么是高案、中间方案和底案？</h4>
              <div className="space-y-2 text-sm text-slate-400">
                <p><span className="text-green-400 font-medium">高案</span>：您的理想目标，代表最有利的结果。</p>
                <p><span className="text-blue-400 font-medium">中间方案</span>：务实可行的选择，平衡各方利益。</p>
                <p><span className="text-red-400 font-medium">底案</span>：您的最低可接受条件，是谈判底线。</p>
              </div>
            </div>
          </div>
        </div>

        {/* AI生成按钮 */}
        <button
          onClick={generateGoals}
          disabled={isGeneratingGoals || !selfCountry || !selectedTopic}
          className="w-full px-8 py-4 bg-gradient-to-r from-green-500 to-green-600 hover:from-green-400 hover:to-green-500 disabled:from-slate-600 disabled:to-slate-700 disabled:cursor-not-allowed text-white rounded-xl transition-all flex items-center justify-center gap-2 mx-auto shadow-lg shadow-green-500/25"
        >
          {isGeneratingGoals ? (
            <>
              <Loader2 className="w-5 h-5 animate-spin" />
              AI 正在分析并生成目标...
            </>
          ) : (
            <>
              <Sparkles className="w-5 h-5" />
              AI 一键生成谈判目标
            </>
          )}
        </button>

        {goalsError && <p className="text-red-400 text-sm text-center">{goalsError}</p>}

        <div className="text-center">
          <button
            onClick={() => setAutoGeneratedGoals({ highCase: '', middleCase: '', bottomLine: '' })}
            className="text-sm text-slate-500 hover:text-slate-300"
          >
            不想使用 AI 生成？手动输入 →
          </button>
        </div>
      </div>
    ) : (
      <div className="space-y-6">
        {/* 已生成的目标预览 + 编辑 */}
        <div className="bg-green-900/20 rounded-2xl border border-green-700/30 p-6">
          <div className="flex items-center justify-between mb-4">
            <div className="flex items-center gap-2">
              <Check className="w-5 h-5 text-green-400" />
              <span className="text-green-400 font-medium">AI 目标已生成</span>
            </div>
            <button
              onClick={() => setAutoGeneratedGoals(null)}
              className="text-sm text-slate-400 hover:text-slate-300 flex items-center gap-1"
            >
              <RefreshCw className="w-4 h-4" />
              重新生成
            </button>
          </div>

          {/* 高案编辑 */}
          <div className="mb-4 p-4 rounded-xl bg-green-900/20 border border-green-700/30">
            <div className="flex items-center gap-2 mb-2">
              <span className="px-2 py-0.5 rounded text-xs bg-green-500/20 text-green-400">高案</span>
              <span className="text-xs text-slate-400">理想目标</span>
            </div>
            <input
              type="text"
              value={highCaseTitle}
              onChange={(e) => {
                setHighCaseTitle(e.target.value);
                updateHighCase(e.target.value, highCaseDesc);
              }}
              placeholder="标题"
              className="w-full mb-2 px-3 py-2 bg-slate-900/50 border border-slate-700/50 rounded-lg text-white text-sm"
            />
            <textarea
              value={highCaseDesc}
              onChange={(e) => {
                setHighCaseDesc(e.target.value);
                updateHighCase(highCaseTitle, e.target.value);
              }}
              rows={3}
              className="w-full px-4 py-3 bg-slate-900/50 border border-slate-700/50 rounded-xl text-white placeholder-slate-500 focus:outline-none focus:border-green-500/50 resize-none"
            />
          </div>

          {/* 中间方案编辑 */}
          <div className="mb-4 p-4 rounded-xl bg-blue-900/20 border border-blue-700/30">
            <div className="flex items-center gap-2 mb-2">
              <span className="px-2 py-0.5 rounded text-xs bg-blue-500/20 text-blue-400">中间</span>
              <span className="text-xs text-slate-400">务实选择</span>
            </div>
            <input
              type="text"
              value={middleCaseTitle}
              onChange={(e) => {
                setMiddleCaseTitle(e.target.value);
                updateMiddleCase(e.target.value, middleCaseDesc);
              }}
              className="w-full mb-2 px-3 py-2 bg-slate-900/50 border border-slate-700/50 rounded-lg text-white text-sm"
            />
            <textarea
              value={middleCaseDesc}
              onChange={(e) => {
                setMiddleCaseDesc(e.target.value);
                updateMiddleCase(middleCaseTitle, e.target.value);
              }}
              rows={3}
              className="w-full px-4 py-3 bg-slate-900/50 border border-slate-700/50 rounded-xl text-white placeholder-slate-500 focus:outline-none focus:border-blue-500/50 resize-none"
            />
          </div>

          {/* 底案编辑 */}
          <div className="p-4 rounded-xl bg-red-900/20 border border-red-700/30">
            <div className="flex items-center gap-2 mb-2">
              <span className="px-2 py-0.5 rounded text-xs bg-red-500/20 text-red-400">底案</span>
              <span className="text-xs text-slate-400">最低可接受</span>
            </div>
            <input
              type="text"
              value={bottomLineTitle}
              onChange={(e) => {
                setBottomLineTitle(e.target.value);
                updateBottomLine(e.target.value, bottomLineDesc);
              }}
              className="w-full mb-2 px-3 py-2 bg-slate-900/50 border border-slate-700/50 rounded-lg text-white text-sm"
            />
            <textarea
              value={bottomLineDesc}
              onChange={(e) => {
                setBottomLineDesc(e.target.value);
                updateBottomLine(bottomLineTitle, e.target.value);
              }}
              rows={3}
              className="w-full px-4 py-3 bg-slate-900/50 border border-slate-700/50 rounded-xl text-white placeholder-slate-500 focus:outline-none focus:border-red-500/50 resize-none"
            />
            <div className="mt-3 flex items-start gap-2 text-xs text-slate-400">
              <AlertCircle className="w-4 h-4 mt-0.5 flex-shrink-0" />
              <p>底线是您必须守护的核心利益，谈判中不应轻易让步</p>
            </div>
          </div>
        </div>
      </div>
    )}
  </motion.div>
)}

          {/* 步骤6: 议题顺序 */}
          {currentStep === 'issues' && (
            <motion.div
              key="issues"
              initial={{ opacity: 0, x: 20 }}
              animate={{ opacity: 1, x: 0 }}
              exit={{ opacity: 0, x: -20 }}
              className="space-y-6"
            >
              <div className="text-center mb-6">
                <h2 className="text-xl font-semibold text-white mb-2 flex items-center justify-center gap-2">
                  <ListOrdered className="w-5 h-5 text-amber-400" />
                  谈判议题顺序
                </h2>
                <p className="text-sm text-slate-500">
                  选择要讨论的议题，并设置讨论顺序（建议先易后难）
                </p>
              </div>

              {issues.length > 0 ? (
                <div className="space-y-3">
                  {issues
                    .filter(issue => issue.isSelected)
                    .sort((a, b) => (a.order || 0) - (b.order || 0))
                    .map((issue, index) => (
                      <motion.div
                        key={issue.id}
                        initial={{ opacity: 0, y: 10 }}
                        animate={{ opacity: 1, y: 0 }}
                        transition={{ delay: index * 0.05 }}
                        className="bg-slate-900/50 rounded-xl border border-slate-700/50 overflow-hidden"
                      >
                        <div className="flex items-center gap-3 p-4">
                          {/* 排序控制 */}
                          <div className="flex flex-col gap-1">
                            <button
                              onClick={() => moveIssueUp(issue.id)}
                              disabled={index === 0}
                              className="p-1 hover:bg-slate-800 rounded disabled:opacity-30"
                            >
                              <ChevronUp className="w-4 h-4 text-slate-400" />
                            </button>
                            <span className="w-6 h-6 rounded-full bg-amber-500/20 text-amber-400 text-xs font-medium flex items-center justify-center">
                              {index + 1}
                            </span>
                            <button
                              onClick={() => moveIssueDown(issue.id)}
                              disabled={index === issues.filter(i => i.isSelected).length - 1}
                              className="p-1 hover:bg-slate-800 rounded disabled:opacity-30"
                            >
                              <ChevronDown className="w-4 h-4 text-slate-400" />
                            </button>
                          </div>

                          {/* 议题信息 */}
                          <div className="flex-1">
                            <div className="flex items-center gap-2 mb-1">
                              <h4 className="text-white font-medium">{issue.title}</h4>
                              <span className={`px-2 py-0.5 text-xs rounded ${
                                issue.difficulty === 'easy' ? 'bg-green-500/20 text-green-400' :
                                issue.difficulty === 'medium' ? 'bg-yellow-500/20 text-yellow-400' :
                                'bg-red-500/20 text-red-400'
                              }`}>
                                {issue.difficulty === 'easy' ? '简单' : issue.difficulty === 'medium' ? '中等' : '困难'}
                              </span>
                            </div>
                            <p className="text-sm text-slate-400">{issue.description}</p>
                          </div>

                          {/* 展开/收起 */}
                          <button
                            onClick={() => setExpandedIssue(expandedIssue === issue.id ? null : issue.id)}
                            className="p-2 hover:bg-slate-800 rounded-lg transition-colors"
                          >
                            {expandedIssue === issue.id ? (
                              <ChevronUp className="w-4 h-4 text-slate-400" />
                            ) : (
                              <ChevronDown className="w-4 h-4 text-slate-400" />
                            )}
                          </button>
                        </div>

                        {/* 展开详情 */}
                        <AnimatePresence>
                          {expandedIssue === issue.id && (
                            <motion.div
                              initial={{ height: 0 }}
                              animate={{ height: 'auto' }}
                              exit={{ height: 0 }}
                              className="border-t border-slate-700/50 p-4 space-y-3"
                            >
                              <div>
                                <p className="text-xs text-slate-500 mb-1">争议焦点</p>
                                <p className="text-sm text-slate-300">{issue.controversy}</p>
                              </div>
                              <div className="grid md:grid-cols-2 gap-3">
                                <div className="bg-amber-900/20 rounded-lg p-3">
                                  <p className="text-xs text-amber-400 mb-1">己方立场</p>
                                  <p className="text-sm text-slate-300">{issue.selfPosition}</p>
                                </div>
                                <div className="bg-red-900/20 rounded-lg p-3">
                                  <p className="text-xs text-red-400 mb-1">对方立场</p>
                                  <p className="text-sm text-slate-300">{issue.opponentPosition}</p>
                                </div>
                              </div>
                            </motion.div>
                          )}
                        </AnimatePresence>
                      </motion.div>
                    ))}

                  {/* 未选中的议题 */}
                  {issues.filter(i => !i.isSelected).length > 0 && (
                    <div className="mt-6">
                      <p className="text-sm text-slate-500 mb-3">其他可议题（点击选中）</p>
                      <div className="space-y-2">
                        {issues
                          .filter(issue => !issue.isSelected)
                          .map((issue) => (
                            <button
                              key={issue.id}
                              onClick={() => toggleIssue(issue.id)}
                              className="w-full flex items-center gap-3 p-3 bg-slate-800/30 rounded-xl border border-slate-700/30 hover:border-slate-600 transition-colors text-left"
                            >
                              <div className="w-5 h-5 rounded border border-slate-600 flex items-center justify-center">
                                <Check className="w-3 h-3 text-transparent" />
                              </div>
                              <div className="flex-1">
                                <p className="text-sm text-slate-400">{issue.title}</p>
                              </div>
                            </button>
                          ))}
                      </div>
                    </div>
                  )}
                </div>
              ) : (
                <div className="text-center py-12">
                  <ListOrdered className="w-12 h-12 mx-auto text-slate-500 mb-4" />
                  <p className="text-slate-400">暂无议题</p>
                  <p className="text-sm text-slate-500">请先生成背景故事</p>
                </div>
              )}
            </motion.div>
          )}

          {/* 步骤6: 完成 */}
          {currentStep === 'complete' && (
            <motion.div
              key="complete"
              initial={{ opacity: 0, scale: 0.95 }}
              animate={{ opacity: 1, scale: 1 }}
              className="text-center py-12"
            >
              <div className="w-20 h-20 mx-auto mb-6 rounded-full bg-green-500/20 flex items-center justify-center">
                <svg className="w-10 h-10 text-green-400" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M5 13l4 4L19 7" />
                </svg>
              </div>
              <h2 className="text-2xl font-bold text-white mb-3">配置完成</h2>
              <p className="text-slate-400 mb-8">准备开始谈判模拟</p>

              {/* 配置摘要 */}
              <div className="max-w-md mx-auto bg-slate-900/50 rounded-2xl border border-slate-700/50 p-6 text-left space-y-4">
                <div className="flex items-start gap-3">
                  <span className="text-2xl">{selectedTopic?.category === 'trade' ? '📦' : selectedTopic?.category === 'peace' ? '🕊️' : '🌍'}</span>
                  <div>
                    <p className="text-xs text-slate-500 uppercase">谈判主题</p>
                    <p className="text-white font-medium">{selectedTopic?.name}</p>
                  </div>
                </div>
                <div className="h-px bg-slate-700/50" />
                <div className="flex gap-4">
                  <div className="flex-1">
                    <p className="text-xs text-slate-500 uppercase">己方</p>
                    <p className="text-white">
                      {countries.find((c) => c.id === selfCountry)?.flag}{' '}
                      {countries.find((c) => c.id === selfCountry)?.name}
                    </p>
                  </div>
                  <div className="flex-1">
                    <p className="text-xs text-slate-500 uppercase">对方</p>
                    <p className="text-white">
                      {countries.find((c) => c.id === opponentCountry)?.flag}{' '}
                      {countries.find((c) => c.id === opponentCountry)?.name}
                    </p>
                  </div>
                </div>
                {opponentPersonality && (
                  <>
                    <div className="h-px bg-slate-700/50" />
                    <div>
                      <p className="text-xs text-slate-500 uppercase">对方风格</p>
                      <p className="text-white">{opponentPersonality}</p>
                    </div>
                  </>
                )}
                <div className="h-px bg-slate-700/50" />
                <div>
                  <p className="text-xs text-slate-500 uppercase">谈判目标 ({objectives.length})</p>
                  <div className="mt-2 space-y-1">
                    {objectives.slice(0, 3).map((obj, i) => (
                      <p key={i} className="text-sm text-slate-300">{obj}</p>
                    ))}
                    {objectives.length > 3 && (
                      <p className="text-sm text-slate-500">...还有{objectives.length - 3}个目标</p>
                    )}
                  </div>
                </div>
              </div>
            </motion.div>
          )}
        </AnimatePresence>

        {/* 导航按钮 */}
        <div className="flex justify-between mt-12">
          <button
            onClick={handleBack}
            disabled={currentStepIndex === 0}
            className="px-6 py-3 bg-slate-800 hover:bg-slate-700 disabled:opacity-50 disabled:cursor-not-allowed text-white rounded-xl transition-colors flex items-center gap-2"
          >
            <svg className="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M15 19l-7-7 7-7" />
            </svg>
            上一步
          </button>

          {currentStep === 'complete' ? (
            <button
              onClick={handleComplete}
              className="px-8 py-3 bg-gradient-to-r from-amber-500 to-amber-600 hover:from-amber-400 hover:to-amber-500 text-white font-medium rounded-xl transition-all shadow-lg shadow-amber-500/25"
            >
              开始谈判
            </button>
          ) : (
            <button
              onClick={handleNext}
              disabled={
                (currentStep === 'topic' && !selectedTopic) ||
                (currentStep === 'parties' && (!selfCountry || !opponentCountry)) ||
                (currentStep === 'goals' &&
                    (difficulty === 'medium'
                          ? (!selectedHighProposal || !selectedMiddleProposal || !selectedBottomLineProposal)
                          : (!highCase.trim() || !bottomLine.trim())
                    )
                  ) ||
                (currentStep === 'issues' && issues.filter(i => i.isSelected).length === 0) ||
                currentStepIndex === steps.length - 1
              }
              className="px-6 py-3 bg-amber-600 hover:bg-amber-500 disabled:bg-slate-700 disabled:cursor-not-allowed text-white rounded-xl transition-colors flex items-center gap-2"
            >
              下一步
              <svg className="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 5l7 7-7 7" />
              </svg>
            </button>
          )}
        </div>
      </div>
    </div>
  );
}
